<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once 'templates/header.phtml';
?>

<div class="container">
    <!-- Sección para mostrar el detalle de un solo ítem -->
    <?php if(isset($item)): ?>
        <h1>Detalle del Ítem: <?php echo $item->nombre; ?></h1>
        <p>Descripción: <?php echo $item->descripcion; ?></p>
        <p>Precio: <?php echo $item->precio; ?></p>
        <p>Categoría: <?php echo $item->id_categoria; ?> <!-- poner el nombre de la categoría --> </p>
    <?php endif; ?>
  
</div>

<?php require_once 'templates/footer.phtml'; ?>
