<?php require_once 'templates/header.phtml'; ?>

<h1>Bienvenido a nuestra tienda</h1>
<h2>Categorías de productos</h2>

<div class="container">
    <div class="row"> 
        <div class="col-12">
            <h1>Categorías</h1>
            <!-- Botón para agregar nueva categoría -->
            <a href="agregar-categoria" class="btn btn-primary">
                Agregar nueva categoría
            </a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($categorias as $categoria): ?>
                        <tr>
                            <td>
                                <!-- Enlace para la categoría -->
                                <a href="productos-por-categoria/<?= $categoria->id_categoria; ?>" class="btn btn-link">
                                    <?= $categoria->nombre_categoria; ?>
                                </a>
                            </td>
                            <td>
                                <!-- Botón para editar -->
                                <a href="<?= BASE_URL ?>mostrar-editar-categoria/<?= $categoria->id_categoria ?>" class="btn btn-warning">
                                    Editar
                                </a>
                            </td>
                            <td>
                                <!-- Botón para eliminar -->
                                <a href="<?= BASE_URL ?>borrarCategoria/<?= $categoria->id_categoria ?>" class="btn btn-danger">
                                    Eliminar
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php require_once 'templates/footer.phtml'; ?>
