<?php

require_once 'templates/header.phtml';
?>

<div class="container">
    <!-- Sección para mostrar el detalle de un solo ítem -->
    <?php if(isset($item)): ?>
        <h1>Detalle del Ítem: <?= $item->nombre; ?></h1>
        <p>Descripción: <?= $item->descripcion; ?></p>
        <p>Precio: <?= $item->precio; ?></p>
        <p>Categoría: <?= $item->id_categoria; ?> <!-- poner el nombre de la categoría --> </p>
    <?php endif; ?>
  
</div>

<?php require_once 'templates/footer.phtml'; ?>
