<?php
require_once 'templates/header.phtml';
?>

<div class="container mt-5">
    <h1>Editar producto existente</h1>
    <form action="<?= BASE_URL ?>guardar-cambios-producto" method="POST">

        <!-- Campo oculto para almacenar el ID del producto -->
        <input type="hidden" name="id" value="<?= $producto->id ?>">

        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" value="<?= $producto->nombre ?>" required>
        </div>
        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripcion</label>
            <input type="text" class="form-control" id="descripcion" name="descripcion" value="<?= $producto->descripcion ?>" required>
        </div>
        <div class="mb-3">
            <label for="precio" class="form-label">Precio</label>
            <input type="number" step="0.01" class="form-control" id="precio" name="precio" value="<?= $producto->precio ?>" required>
        </div>
        <div class="mb-3">
            <label for="id_categoria" class="form-label">Categoría</label>
            <select class="form-control" id="id_categoria" name="id_categoria" required>
                <option value="">--Seleccione una categoría--</option>
                <?php foreach ($categorias as $categoria) : ?>
                    <option value="<?= $categoria->id ?>" <?= $categoria->id == $producto->id_categoria ? 'selected' : '' ?>><?= $categoria->nombre ?></option>
                <?php endforeach; ?>
                
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
    </form>
</div>
<?php require_once 'templates/footer.phtml'; ?>
