<?php require_once 'templates/header.phtml'; ?>

<div class="container mt-5">
    <h1>Agregar Categoría</h1>
    <form action="route.php?action=agregar-categoria" method="POST">

        <div class="mb-3">
            <label for="nombre_categoria" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="nombre_categoria" name="nombre_categoria" required>
        </div>
        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción</label>
            <input type="text" class="form-control" id="descripcion" name="descripcion" required>
        </div>
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
</div>

<?php require_once 'templates/footer.phtml'; ?>
