<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once 'templates/header.phtml'; ?>

<h1>Listado de Ítems</h1>

<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Precio</th>
                        <th>ID de Categoría</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($productos as $item): ?>
                        <tr>
                            <td><?php echo $item->id; ?></td>
                            <td><a href="detalle-item/<?php echo $item->id; ?>"><?php echo $item->nombre; ?></a></td>
                            <td><?php echo $item->descripcion; ?></td>
                            <td><?php echo $item->precio; ?></td>
                            <td><?php echo $item->id_categoria; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php require_once 'templates/footer.phtml'; ?>
