
<?php require_once 'templates/header.phtml'; ?>
<h1>Productos por Categoría</h1>

<!-- Opción para seleccionar categorías -->
<select onchange="location = this.value;">
  <option>Seleccionar Categoría</option>
  <?php foreach ($categorias as $categoria): ?>
    <option value="<?= BASE_URL ?>productos-por-categoria/<?= $categoria->id; ?>">
    <?= $categoria->nombre; ?>

    </option>
  <?php endforeach; ?>
</select>

<!-- Tabla de productos -->
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Precio</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($productos as $producto): ?>
      <tr>
            <td><?= $producto->id; ?></td>
            <td><?= $producto->nombre; ?></td>
            <td><?= $producto->descripcion; ?></td>
            <td><?= $producto->precio; ?></td>

      </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<?php require_once 'templates/footer.phtml'; ?>
